# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/facosta/kevoree-contiki

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/facosta/kevoree-contiki

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/facosta/kevoree-contiki/CMakeFiles /home/facosta/kevoree-contiki/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/facosta/kevoree-contiki/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/Comparekevoree.o: src/Comparekevoree.c.o
.PHONY : src/Comparekevoree.o

# target to build an object file
src/Comparekevoree.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Comparekevoree.c.o
.PHONY : src/Comparekevoree.c.o

src/Comparekevoree.i: src/Comparekevoree.c.i
.PHONY : src/Comparekevoree.i

# target to preprocess a source file
src/Comparekevoree.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Comparekevoree.c.i
.PHONY : src/Comparekevoree.c.i

src/Comparekevoree.s: src/Comparekevoree.c.s
.PHONY : src/Comparekevoree.s

# target to generate assembly for a file
src/Comparekevoree.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Comparekevoree.c.s
.PHONY : src/Comparekevoree.c.s

src/ComponentInstance.o: src/ComponentInstance.c.o
.PHONY : src/ComponentInstance.o

# target to build an object file
src/ComponentInstance.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ComponentInstance.c.o
.PHONY : src/ComponentInstance.c.o

src/ComponentInstance.i: src/ComponentInstance.c.i
.PHONY : src/ComponentInstance.i

# target to preprocess a source file
src/ComponentInstance.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ComponentInstance.c.i
.PHONY : src/ComponentInstance.c.i

src/ComponentInstance.s: src/ComponentInstance.c.s
.PHONY : src/ComponentInstance.s

# target to generate assembly for a file
src/ComponentInstance.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ComponentInstance.c.s
.PHONY : src/ComponentInstance.c.s

src/ComponentType.o: src/ComponentType.c.o
.PHONY : src/ComponentType.o

# target to build an object file
src/ComponentType.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ComponentType.c.o
.PHONY : src/ComponentType.c.o

src/ComponentType.i: src/ComponentType.c.i
.PHONY : src/ComponentType.i

# target to preprocess a source file
src/ComponentType.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ComponentType.c.i
.PHONY : src/ComponentType.c.i

src/ComponentType.s: src/ComponentType.c.s
.PHONY : src/ComponentType.s

# target to generate assembly for a file
src/ComponentType.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ComponentType.c.s
.PHONY : src/ComponentType.c.s

src/ContainerNode.o: src/ContainerNode.c.o
.PHONY : src/ContainerNode.o

# target to build an object file
src/ContainerNode.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ContainerNode.c.o
.PHONY : src/ContainerNode.c.o

src/ContainerNode.i: src/ContainerNode.c.i
.PHONY : src/ContainerNode.i

# target to preprocess a source file
src/ContainerNode.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ContainerNode.c.i
.PHONY : src/ContainerNode.c.i

src/ContainerNode.s: src/ContainerNode.c.s
.PHONY : src/ContainerNode.s

# target to generate assembly for a file
src/ContainerNode.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ContainerNode.c.s
.PHONY : src/ContainerNode.c.s

src/ContainerRoot.o: src/ContainerRoot.c.o
.PHONY : src/ContainerRoot.o

# target to build an object file
src/ContainerRoot.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ContainerRoot.c.o
.PHONY : src/ContainerRoot.c.o

src/ContainerRoot.i: src/ContainerRoot.c.i
.PHONY : src/ContainerRoot.i

# target to preprocess a source file
src/ContainerRoot.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ContainerRoot.c.i
.PHONY : src/ContainerRoot.c.i

src/ContainerRoot.s: src/ContainerRoot.c.s
.PHONY : src/ContainerRoot.s

# target to generate assembly for a file
src/ContainerRoot.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ContainerRoot.c.s
.PHONY : src/ContainerRoot.c.s

src/DefaultFactorykevoree.o: src/DefaultFactorykevoree.c.o
.PHONY : src/DefaultFactorykevoree.o

# target to build an object file
src/DefaultFactorykevoree.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/DefaultFactorykevoree.c.o
.PHONY : src/DefaultFactorykevoree.c.o

src/DefaultFactorykevoree.i: src/DefaultFactorykevoree.c.i
.PHONY : src/DefaultFactorykevoree.i

# target to preprocess a source file
src/DefaultFactorykevoree.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/DefaultFactorykevoree.c.i
.PHONY : src/DefaultFactorykevoree.c.i

src/DefaultFactorykevoree.s: src/DefaultFactorykevoree.c.s
.PHONY : src/DefaultFactorykevoree.s

# target to generate assembly for a file
src/DefaultFactorykevoree.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/DefaultFactorykevoree.c.s
.PHONY : src/DefaultFactorykevoree.c.s

src/DeployUnit.o: src/DeployUnit.c.o
.PHONY : src/DeployUnit.o

# target to build an object file
src/DeployUnit.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/DeployUnit.c.o
.PHONY : src/DeployUnit.c.o

src/DeployUnit.i: src/DeployUnit.c.i
.PHONY : src/DeployUnit.i

# target to preprocess a source file
src/DeployUnit.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/DeployUnit.c.i
.PHONY : src/DeployUnit.c.i

src/DeployUnit.s: src/DeployUnit.c.s
.PHONY : src/DeployUnit.s

# target to generate assembly for a file
src/DeployUnit.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/DeployUnit.c.s
.PHONY : src/DeployUnit.c.s

src/Group.o: src/Group.c.o
.PHONY : src/Group.o

# target to build an object file
src/Group.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Group.c.o
.PHONY : src/Group.c.o

src/Group.i: src/Group.c.i
.PHONY : src/Group.i

# target to preprocess a source file
src/Group.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Group.c.i
.PHONY : src/Group.c.i

src/Group.s: src/Group.c.s
.PHONY : src/Group.s

# target to generate assembly for a file
src/Group.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Group.c.s
.PHONY : src/Group.c.s

src/GroupType.o: src/GroupType.c.o
.PHONY : src/GroupType.o

# target to build an object file
src/GroupType.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GroupType.c.o
.PHONY : src/GroupType.c.o

src/GroupType.i: src/GroupType.c.i
.PHONY : src/GroupType.i

# target to preprocess a source file
src/GroupType.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GroupType.c.i
.PHONY : src/GroupType.c.i

src/GroupType.s: src/GroupType.c.s
.PHONY : src/GroupType.s

# target to generate assembly for a file
src/GroupType.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GroupType.c.s
.PHONY : src/GroupType.c.s

src/Instance.o: src/Instance.c.o
.PHONY : src/Instance.o

# target to build an object file
src/Instance.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Instance.c.o
.PHONY : src/Instance.c.o

src/Instance.i: src/Instance.c.i
.PHONY : src/Instance.i

# target to preprocess a source file
src/Instance.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Instance.c.i
.PHONY : src/Instance.c.i

src/Instance.s: src/Instance.c.s
.PHONY : src/Instance.s

# target to generate assembly for a file
src/Instance.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Instance.c.s
.PHONY : src/Instance.c.s

src/NamedElement.o: src/NamedElement.c.o
.PHONY : src/NamedElement.o

# target to build an object file
src/NamedElement.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NamedElement.c.o
.PHONY : src/NamedElement.c.o

src/NamedElement.i: src/NamedElement.c.i
.PHONY : src/NamedElement.i

# target to preprocess a source file
src/NamedElement.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NamedElement.c.i
.PHONY : src/NamedElement.c.i

src/NamedElement.s: src/NamedElement.c.s
.PHONY : src/NamedElement.s

# target to generate assembly for a file
src/NamedElement.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NamedElement.c.s
.PHONY : src/NamedElement.c.s

src/NetworkInfo.o: src/NetworkInfo.c.o
.PHONY : src/NetworkInfo.o

# target to build an object file
src/NetworkInfo.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NetworkInfo.c.o
.PHONY : src/NetworkInfo.c.o

src/NetworkInfo.i: src/NetworkInfo.c.i
.PHONY : src/NetworkInfo.i

# target to preprocess a source file
src/NetworkInfo.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NetworkInfo.c.i
.PHONY : src/NetworkInfo.c.i

src/NetworkInfo.s: src/NetworkInfo.c.s
.PHONY : src/NetworkInfo.s

# target to generate assembly for a file
src/NetworkInfo.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NetworkInfo.c.s
.PHONY : src/NetworkInfo.c.s

src/NetworkProperty.o: src/NetworkProperty.c.o
.PHONY : src/NetworkProperty.o

# target to build an object file
src/NetworkProperty.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NetworkProperty.c.o
.PHONY : src/NetworkProperty.c.o

src/NetworkProperty.i: src/NetworkProperty.c.i
.PHONY : src/NetworkProperty.i

# target to preprocess a source file
src/NetworkProperty.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NetworkProperty.c.i
.PHONY : src/NetworkProperty.c.i

src/NetworkProperty.s: src/NetworkProperty.c.s
.PHONY : src/NetworkProperty.s

# target to generate assembly for a file
src/NetworkProperty.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NetworkProperty.c.s
.PHONY : src/NetworkProperty.c.s

src/NodeLink.o: src/NodeLink.c.o
.PHONY : src/NodeLink.o

# target to build an object file
src/NodeLink.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NodeLink.c.o
.PHONY : src/NodeLink.c.o

src/NodeLink.i: src/NodeLink.c.i
.PHONY : src/NodeLink.i

# target to preprocess a source file
src/NodeLink.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NodeLink.c.i
.PHONY : src/NodeLink.c.i

src/NodeLink.s: src/NodeLink.c.s
.PHONY : src/NodeLink.s

# target to generate assembly for a file
src/NodeLink.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NodeLink.c.s
.PHONY : src/NodeLink.c.s

src/NodeNetwork.o: src/NodeNetwork.c.o
.PHONY : src/NodeNetwork.o

# target to build an object file
src/NodeNetwork.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NodeNetwork.c.o
.PHONY : src/NodeNetwork.c.o

src/NodeNetwork.i: src/NodeNetwork.c.i
.PHONY : src/NodeNetwork.i

# target to preprocess a source file
src/NodeNetwork.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NodeNetwork.c.i
.PHONY : src/NodeNetwork.c.i

src/NodeNetwork.s: src/NodeNetwork.c.s
.PHONY : src/NodeNetwork.s

# target to generate assembly for a file
src/NodeNetwork.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NodeNetwork.c.s
.PHONY : src/NodeNetwork.c.s

src/NodeType.o: src/NodeType.c.o
.PHONY : src/NodeType.o

# target to build an object file
src/NodeType.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NodeType.c.o
.PHONY : src/NodeType.c.o

src/NodeType.i: src/NodeType.c.i
.PHONY : src/NodeType.i

# target to preprocess a source file
src/NodeType.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NodeType.c.i
.PHONY : src/NodeType.c.i

src/NodeType.s: src/NodeType.c.s
.PHONY : src/NodeType.s

# target to generate assembly for a file
src/NodeType.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/NodeType.c.s
.PHONY : src/NodeType.c.s

src/PortType.o: src/PortType.c.o
.PHONY : src/PortType.o

# target to build an object file
src/PortType.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/PortType.c.o
.PHONY : src/PortType.c.o

src/PortType.i: src/PortType.c.i
.PHONY : src/PortType.i

# target to preprocess a source file
src/PortType.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/PortType.c.i
.PHONY : src/PortType.c.i

src/PortType.s: src/PortType.c.s
.PHONY : src/PortType.s

# target to generate assembly for a file
src/PortType.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/PortType.c.s
.PHONY : src/PortType.c.s

src/PortTypeMapping.o: src/PortTypeMapping.c.o
.PHONY : src/PortTypeMapping.o

# target to build an object file
src/PortTypeMapping.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/PortTypeMapping.c.o
.PHONY : src/PortTypeMapping.c.o

src/PortTypeMapping.i: src/PortTypeMapping.c.i
.PHONY : src/PortTypeMapping.i

# target to preprocess a source file
src/PortTypeMapping.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/PortTypeMapping.c.i
.PHONY : src/PortTypeMapping.c.i

src/PortTypeMapping.s: src/PortTypeMapping.c.s
.PHONY : src/PortTypeMapping.s

# target to generate assembly for a file
src/PortTypeMapping.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/PortTypeMapping.c.s
.PHONY : src/PortTypeMapping.c.s

src/PortTypeRef.o: src/PortTypeRef.c.o
.PHONY : src/PortTypeRef.o

# target to build an object file
src/PortTypeRef.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/PortTypeRef.c.o
.PHONY : src/PortTypeRef.c.o

src/PortTypeRef.i: src/PortTypeRef.c.i
.PHONY : src/PortTypeRef.i

# target to preprocess a source file
src/PortTypeRef.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/PortTypeRef.c.i
.PHONY : src/PortTypeRef.c.i

src/PortTypeRef.s: src/PortTypeRef.c.s
.PHONY : src/PortTypeRef.s

# target to generate assembly for a file
src/PortTypeRef.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/PortTypeRef.c.s
.PHONY : src/PortTypeRef.c.s

src/Repository.o: src/Repository.c.o
.PHONY : src/Repository.o

# target to build an object file
src/Repository.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Repository.c.o
.PHONY : src/Repository.c.o

src/Repository.i: src/Repository.c.i
.PHONY : src/Repository.i

# target to preprocess a source file
src/Repository.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Repository.c.i
.PHONY : src/Repository.c.i

src/Repository.s: src/Repository.c.s
.PHONY : src/Repository.s

# target to generate assembly for a file
src/Repository.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Repository.c.s
.PHONY : src/Repository.c.s

src/TypeDefinition.o: src/TypeDefinition.c.o
.PHONY : src/TypeDefinition.o

# target to build an object file
src/TypeDefinition.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/TypeDefinition.c.o
.PHONY : src/TypeDefinition.c.o

src/TypeDefinition.i: src/TypeDefinition.c.i
.PHONY : src/TypeDefinition.i

# target to preprocess a source file
src/TypeDefinition.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/TypeDefinition.c.i
.PHONY : src/TypeDefinition.c.i

src/TypeDefinition.s: src/TypeDefinition.c.s
.PHONY : src/TypeDefinition.s

# target to generate assembly for a file
src/TypeDefinition.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/TypeDefinition.c.s
.PHONY : src/TypeDefinition.c.s

src/TypeLibrary.o: src/TypeLibrary.c.o
.PHONY : src/TypeLibrary.o

# target to build an object file
src/TypeLibrary.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/TypeLibrary.c.o
.PHONY : src/TypeLibrary.c.o

src/TypeLibrary.i: src/TypeLibrary.c.i
.PHONY : src/TypeLibrary.i

# target to preprocess a source file
src/TypeLibrary.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/TypeLibrary.c.i
.PHONY : src/TypeLibrary.c.i

src/TypeLibrary.s: src/TypeLibrary.c.s
.PHONY : src/TypeLibrary.s

# target to generate assembly for a file
src/TypeLibrary.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/TypeLibrary.c.s
.PHONY : src/TypeLibrary.c.s

src/TypedElement.o: src/TypedElement.c.o
.PHONY : src/TypedElement.o

# target to build an object file
src/TypedElement.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/TypedElement.c.o
.PHONY : src/TypedElement.c.o

src/TypedElement.i: src/TypedElement.c.i
.PHONY : src/TypedElement.i

# target to preprocess a source file
src/TypedElement.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/TypedElement.c.i
.PHONY : src/TypedElement.c.i

src/TypedElement.s: src/TypedElement.c.s
.PHONY : src/TypedElement.s

# target to generate assembly for a file
src/TypedElement.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/TypedElement.c.s
.PHONY : src/TypedElement.c.s

src/hashmap.o: src/hashmap.c.o
.PHONY : src/hashmap.o

# target to build an object file
src/hashmap.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/hashmap.c.o
.PHONY : src/hashmap.c.o

src/hashmap.i: src/hashmap.c.i
.PHONY : src/hashmap.i

# target to preprocess a source file
src/hashmap.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/hashmap.c.i
.PHONY : src/hashmap.c.i

src/hashmap.s: src/hashmap.c.s
.PHONY : src/hashmap.s

# target to generate assembly for a file
src/hashmap.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/hashmap.c.s
.PHONY : src/hashmap.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.c.s
.PHONY : src/main.c.s

src/realloc.o: src/realloc.c.o
.PHONY : src/realloc.o

# target to build an object file
src/realloc.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/realloc.c.o
.PHONY : src/realloc.c.o

src/realloc.i: src/realloc.c.i
.PHONY : src/realloc.i

# target to preprocess a source file
src/realloc.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/realloc.c.i
.PHONY : src/realloc.c.i

src/realloc.s: src/realloc.c.s
.PHONY : src/realloc.s

# target to generate assembly for a file
src/realloc.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/realloc.c.s
.PHONY : src/realloc.c.s

src/tools.o: src/tools.c.o
.PHONY : src/tools.o

# target to build an object file
src/tools.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tools.c.o
.PHONY : src/tools.c.o

src/tools.i: src/tools.c.i
.PHONY : src/tools.i

# target to preprocess a source file
src/tools.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tools.c.i
.PHONY : src/tools.c.i

src/tools.s: src/tools.c.s
.PHONY : src/tools.s

# target to generate assembly for a file
src/tools.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tools.c.s
.PHONY : src/tools.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... rebuild_cache"
	@echo "... src/Comparekevoree.o"
	@echo "... src/Comparekevoree.i"
	@echo "... src/Comparekevoree.s"
	@echo "... src/ComponentInstance.o"
	@echo "... src/ComponentInstance.i"
	@echo "... src/ComponentInstance.s"
	@echo "... src/ComponentType.o"
	@echo "... src/ComponentType.i"
	@echo "... src/ComponentType.s"
	@echo "... src/ContainerNode.o"
	@echo "... src/ContainerNode.i"
	@echo "... src/ContainerNode.s"
	@echo "... src/ContainerRoot.o"
	@echo "... src/ContainerRoot.i"
	@echo "... src/ContainerRoot.s"
	@echo "... src/DefaultFactorykevoree.o"
	@echo "... src/DefaultFactorykevoree.i"
	@echo "... src/DefaultFactorykevoree.s"
	@echo "... src/DeployUnit.o"
	@echo "... src/DeployUnit.i"
	@echo "... src/DeployUnit.s"
	@echo "... src/Group.o"
	@echo "... src/Group.i"
	@echo "... src/Group.s"
	@echo "... src/GroupType.o"
	@echo "... src/GroupType.i"
	@echo "... src/GroupType.s"
	@echo "... src/Instance.o"
	@echo "... src/Instance.i"
	@echo "... src/Instance.s"
	@echo "... src/NamedElement.o"
	@echo "... src/NamedElement.i"
	@echo "... src/NamedElement.s"
	@echo "... src/NetworkInfo.o"
	@echo "... src/NetworkInfo.i"
	@echo "... src/NetworkInfo.s"
	@echo "... src/NetworkProperty.o"
	@echo "... src/NetworkProperty.i"
	@echo "... src/NetworkProperty.s"
	@echo "... src/NodeLink.o"
	@echo "... src/NodeLink.i"
	@echo "... src/NodeLink.s"
	@echo "... src/NodeNetwork.o"
	@echo "... src/NodeNetwork.i"
	@echo "... src/NodeNetwork.s"
	@echo "... src/NodeType.o"
	@echo "... src/NodeType.i"
	@echo "... src/NodeType.s"
	@echo "... src/PortType.o"
	@echo "... src/PortType.i"
	@echo "... src/PortType.s"
	@echo "... src/PortTypeMapping.o"
	@echo "... src/PortTypeMapping.i"
	@echo "... src/PortTypeMapping.s"
	@echo "... src/PortTypeRef.o"
	@echo "... src/PortTypeRef.i"
	@echo "... src/PortTypeRef.s"
	@echo "... src/Repository.o"
	@echo "... src/Repository.i"
	@echo "... src/Repository.s"
	@echo "... src/TypeDefinition.o"
	@echo "... src/TypeDefinition.i"
	@echo "... src/TypeDefinition.s"
	@echo "... src/TypeLibrary.o"
	@echo "... src/TypeLibrary.i"
	@echo "... src/TypeLibrary.s"
	@echo "... src/TypedElement.o"
	@echo "... src/TypedElement.i"
	@echo "... src/TypedElement.s"
	@echo "... src/hashmap.o"
	@echo "... src/hashmap.i"
	@echo "... src/hashmap.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/realloc.o"
	@echo "... src/realloc.i"
	@echo "... src/realloc.s"
	@echo "... src/tools.o"
	@echo "... src/tools.i"
	@echo "... src/tools.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

